//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarmonyOfEmotions.ServiceDefaults.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HarmonyOfEmotions.ServiceDefaults.Resources.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF.
        /// </summary>
        internal static string Afghanistan {
            get {
                return ResourceManager.GetString("Afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AX.
        /// </summary>
        internal static string Åland_Islands {
            get {
                return ResourceManager.GetString("Åland Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL.
        /// </summary>
        internal static string Albania {
            get {
                return ResourceManager.GetString("Albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZ.
        /// </summary>
        internal static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS.
        /// </summary>
        internal static string American_Samoa {
            get {
                return ResourceManager.GetString("American Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        internal static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AO.
        /// </summary>
        internal static string Angola {
            get {
                return ResourceManager.GetString("Angola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string Anguilla {
            get {
                return ResourceManager.GetString("Anguilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AQ.
        /// </summary>
        internal static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        internal static string Antigua_and_Barbuda {
            get {
                return ResourceManager.GetString("Antigua and Barbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR.
        /// </summary>
        internal static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AW.
        /// </summary>
        internal static string Aruba {
            get {
                return ResourceManager.GetString("Aruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU.
        /// </summary>
        internal static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT.
        /// </summary>
        internal static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZ.
        /// </summary>
        internal static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        internal static string Bahamas {
            get {
                return ResourceManager.GetString("Bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH.
        /// </summary>
        internal static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD.
        /// </summary>
        internal static string Bangladesh {
            get {
                return ResourceManager.GetString("Bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        internal static string Barbados {
            get {
                return ResourceManager.GetString("Barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY.
        /// </summary>
        internal static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZ.
        /// </summary>
        internal static string Belize {
            get {
                return ResourceManager.GetString("Belize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BJ.
        /// </summary>
        internal static string Benin {
            get {
                return ResourceManager.GetString("Benin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM.
        /// </summary>
        internal static string Bermuda {
            get {
                return ResourceManager.GetString("Bermuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT.
        /// </summary>
        internal static string Bhutan {
            get {
                return ResourceManager.GetString("Bhutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO.
        /// </summary>
        internal static string Bolivia {
            get {
                return ResourceManager.GetString("Bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BQ.
        /// </summary>
        internal static string Bonaire {
            get {
                return ResourceManager.GetString("Bonaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA.
        /// </summary>
        internal static string Bosnia_and_Herzegovina {
            get {
                return ResourceManager.GetString("Bosnia and Herzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BW.
        /// </summary>
        internal static string Botswana {
            get {
                return ResourceManager.GetString("Botswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BV.
        /// </summary>
        internal static string Bouvet_Island {
            get {
                return ResourceManager.GetString("Bouvet Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BR.
        /// </summary>
        internal static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO.
        /// </summary>
        internal static string British_Indian_Ocean_Territory {
            get {
                return ResourceManager.GetString("British Indian Ocean Territory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG.
        /// </summary>
        internal static string British_Virgin_Islands {
            get {
                return ResourceManager.GetString("British Virgin Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN.
        /// </summary>
        internal static string Brunei_Darussalam {
            get {
                return ResourceManager.GetString("Brunei Darussalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG.
        /// </summary>
        internal static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BF.
        /// </summary>
        internal static string Burkina_Faso {
            get {
                return ResourceManager.GetString("Burkina Faso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI.
        /// </summary>
        internal static string Burundi {
            get {
                return ResourceManager.GetString("Burundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        internal static string Cabo_Verde {
            get {
                return ResourceManager.GetString("Cabo Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KH.
        /// </summary>
        internal static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM.
        /// </summary>
        internal static string Cameroon {
            get {
                return ResourceManager.GetString("Cameroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        internal static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KY.
        /// </summary>
        internal static string Cayman_Islands {
            get {
                return ResourceManager.GetString("Cayman Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF.
        /// </summary>
        internal static string Central_African_Republic {
            get {
                return ResourceManager.GetString("Central African Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        internal static string Chad {
            get {
                return ResourceManager.GetString("Chad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL.
        /// </summary>
        internal static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        internal static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CX.
        /// </summary>
        internal static string Christmas_Island {
            get {
                return ResourceManager.GetString("Christmas Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string Cocos_Islands {
            get {
                return ResourceManager.GetString("Cocos Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO.
        /// </summary>
        internal static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        internal static string Comoros {
            get {
                return ResourceManager.GetString("Comoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CG.
        /// </summary>
        internal static string Congo {
            get {
                return ResourceManager.GetString("Congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK.
        /// </summary>
        internal static string Cook_Islands {
            get {
                return ResourceManager.GetString("Cook Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        internal static string Costa_Rica {
            get {
                return ResourceManager.GetString("Costa Rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        internal static string Côte_d_Ivoire {
            get {
                return ResourceManager.GetString("Côte d\'Ivoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CU.
        /// </summary>
        internal static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW.
        /// </summary>
        internal static string Curaçao {
            get {
                return ResourceManager.GetString("Curaçao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CY.
        /// </summary>
        internal static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ.
        /// </summary>
        internal static string Czechia {
            get {
                return ResourceManager.GetString("Czechia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK.
        /// </summary>
        internal static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJ.
        /// </summary>
        internal static string Djibouti {
            get {
                return ResourceManager.GetString("Djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM.
        /// </summary>
        internal static string Dominica {
            get {
                return ResourceManager.GetString("Dominica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO.
        /// </summary>
        internal static string Dominican_Republic {
            get {
                return ResourceManager.GetString("Dominican Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC.
        /// </summary>
        internal static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EG.
        /// </summary>
        internal static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SV.
        /// </summary>
        internal static string El_Salvador {
            get {
                return ResourceManager.GetString("El Salvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GQ.
        /// </summary>
        internal static string Equatorial_Guinea {
            get {
                return ResourceManager.GetString("Equatorial Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER.
        /// </summary>
        internal static string Eritrea {
            get {
                return ResourceManager.GetString("Eritrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EE.
        /// </summary>
        internal static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZ.
        /// </summary>
        internal static string Eswatini {
            get {
                return ResourceManager.GetString("Eswatini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.
        /// </summary>
        internal static string Ethiopia {
            get {
                return ResourceManager.GetString("Ethiopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK.
        /// </summary>
        internal static string Falkland_Islands {
            get {
                return ResourceManager.GetString("Falkland Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FO.
        /// </summary>
        internal static string Faroe_Islands {
            get {
                return ResourceManager.GetString("Faroe Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FJ.
        /// </summary>
        internal static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI.
        /// </summary>
        internal static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GF.
        /// </summary>
        internal static string French_Guiana {
            get {
                return ResourceManager.GetString("French Guiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PF.
        /// </summary>
        internal static string French_Polynesia {
            get {
                return ResourceManager.GetString("French Polynesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF.
        /// </summary>
        internal static string French_Southern_Territories {
            get {
                return ResourceManager.GetString("French Southern Territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GA.
        /// </summary>
        internal static string Gabon {
            get {
                return ResourceManager.GetString("Gabon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM.
        /// </summary>
        internal static string Gambia {
            get {
                return ResourceManager.GetString("Gambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE.
        /// </summary>
        internal static string Georgia {
            get {
                return ResourceManager.GetString("Georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GH.
        /// </summary>
        internal static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI.
        /// </summary>
        internal static string Gibraltar {
            get {
                return ResourceManager.GetString("Gibraltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR.
        /// </summary>
        internal static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL.
        /// </summary>
        internal static string Greenland {
            get {
                return ResourceManager.GetString("Greenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GD.
        /// </summary>
        internal static string Grenada {
            get {
                return ResourceManager.GetString("Grenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        internal static string Guadeloupe {
            get {
                return ResourceManager.GetString("Guadeloupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GU.
        /// </summary>
        internal static string Guam {
            get {
                return ResourceManager.GetString("Guam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT.
        /// </summary>
        internal static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GG.
        /// </summary>
        internal static string Guernsey {
            get {
                return ResourceManager.GetString("Guernsey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GN.
        /// </summary>
        internal static string Guinea {
            get {
                return ResourceManager.GetString("Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GW.
        /// </summary>
        internal static string Guinea_Bissau {
            get {
                return ResourceManager.GetString("Guinea-Bissau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GY.
        /// </summary>
        internal static string Guyana {
            get {
                return ResourceManager.GetString("Guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT.
        /// </summary>
        internal static string Haiti {
            get {
                return ResourceManager.GetString("Haiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM.
        /// </summary>
        internal static string Heard_Island_and_McDonald_Islands {
            get {
                return ResourceManager.GetString("Heard Island and McDonald Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA.
        /// </summary>
        internal static string Holy_See {
            get {
                return ResourceManager.GetString("Holy See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN.
        /// </summary>
        internal static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK.
        /// </summary>
        internal static string Hong_Kong {
            get {
                return ResourceManager.GetString("Hong Kong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HU.
        /// </summary>
        internal static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS.
        /// </summary>
        internal static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR.
        /// </summary>
        internal static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ.
        /// </summary>
        internal static string Iraq {
            get {
                return ResourceManager.GetString("Iraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        internal static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string Isle_of_Man {
            get {
                return ResourceManager.GetString("Isle of Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL.
        /// </summary>
        internal static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JM.
        /// </summary>
        internal static string Jamaica {
            get {
                return ResourceManager.GetString("Jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JP.
        /// </summary>
        internal static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JE.
        /// </summary>
        internal static string Jersey {
            get {
                return ResourceManager.GetString("Jersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JO.
        /// </summary>
        internal static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KZ.
        /// </summary>
        internal static string Kazakhstan {
            get {
                return ResourceManager.GetString("Kazakhstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KE.
        /// </summary>
        internal static string Kenya {
            get {
                return ResourceManager.GetString("Kenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KI.
        /// </summary>
        internal static string Kiribati {
            get {
                return ResourceManager.GetString("Kiribati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        internal static string Korea {
            get {
                return ResourceManager.GetString("Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KW.
        /// </summary>
        internal static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KG.
        /// </summary>
        internal static string Kyrgyzstan {
            get {
                return ResourceManager.GetString("Kyrgyzstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA.
        /// </summary>
        internal static string Laos {
            get {
                return ResourceManager.GetString("Laos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LV.
        /// </summary>
        internal static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LB.
        /// </summary>
        internal static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        internal static string Lesotho {
            get {
                return ResourceManager.GetString("Lesotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR.
        /// </summary>
        internal static string Liberia {
            get {
                return ResourceManager.GetString("Liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LY.
        /// </summary>
        internal static string Libya {
            get {
                return ResourceManager.GetString("Libya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LI.
        /// </summary>
        internal static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LT.
        /// </summary>
        internal static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU.
        /// </summary>
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        internal static string Macao {
            get {
                return ResourceManager.GetString("Macao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG.
        /// </summary>
        internal static string Madagascar {
            get {
                return ResourceManager.GetString("Madagascar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW.
        /// </summary>
        internal static string Malawi {
            get {
                return ResourceManager.GetString("Malawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY.
        /// </summary>
        internal static string Malaysia {
            get {
                return ResourceManager.GetString("Malaysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV.
        /// </summary>
        internal static string Maldives {
            get {
                return ResourceManager.GetString("Maldives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML.
        /// </summary>
        internal static string Mali {
            get {
                return ResourceManager.GetString("Mali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MH.
        /// </summary>
        internal static string Marshall_Islands {
            get {
                return ResourceManager.GetString("Marshall Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ.
        /// </summary>
        internal static string Martinique {
            get {
                return ResourceManager.GetString("Martinique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR.
        /// </summary>
        internal static string Mauritania {
            get {
                return ResourceManager.GetString("Mauritania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU.
        /// </summary>
        internal static string Mauritius {
            get {
                return ResourceManager.GetString("Mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YT.
        /// </summary>
        internal static string Mayotte {
            get {
                return ResourceManager.GetString("Mayotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MX.
        /// </summary>
        internal static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM.
        /// </summary>
        internal static string Micronesia {
            get {
                return ResourceManager.GetString("Micronesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD.
        /// </summary>
        internal static string Moldova {
            get {
                return ResourceManager.GetString("Moldova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN.
        /// </summary>
        internal static string Mongolia {
            get {
                return ResourceManager.GetString("Mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME.
        /// </summary>
        internal static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string Montserrat {
            get {
                return ResourceManager.GetString("Montserrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA.
        /// </summary>
        internal static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZ.
        /// </summary>
        internal static string Mozambique {
            get {
                return ResourceManager.GetString("Mozambique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        internal static string Myanmar {
            get {
                return ResourceManager.GetString("Myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string Namibia {
            get {
                return ResourceManager.GetString("Namibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        internal static string Nauru {
            get {
                return ResourceManager.GetString("Nauru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NP.
        /// </summary>
        internal static string Nepal {
            get {
                return ResourceManager.GetString("Nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC.
        /// </summary>
        internal static string New_Caledonia {
            get {
                return ResourceManager.GetString("New Caledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZ.
        /// </summary>
        internal static string New_Zealand {
            get {
                return ResourceManager.GetString("New Zealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NI.
        /// </summary>
        internal static string Nicaragua {
            get {
                return ResourceManager.GetString("Nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        internal static string Niger {
            get {
                return ResourceManager.GetString("Niger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        internal static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NU.
        /// </summary>
        internal static string Niue {
            get {
                return ResourceManager.GetString("Niue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF.
        /// </summary>
        internal static string Norfolk_Island {
            get {
                return ResourceManager.GetString("Norfolk Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP.
        /// </summary>
        internal static string North_Korea {
            get {
                return ResourceManager.GetString("North Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MK.
        /// </summary>
        internal static string North_Macedonia {
            get {
                return ResourceManager.GetString("North Macedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string Northern_Ireland {
            get {
                return ResourceManager.GetString("Northern Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        internal static string Northern_Mariana_Islands {
            get {
                return ResourceManager.GetString("Northern Mariana Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OM.
        /// </summary>
        internal static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK.
        /// </summary>
        internal static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PW.
        /// </summary>
        internal static string Palau {
            get {
                return ResourceManager.GetString("Palau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS.
        /// </summary>
        internal static string Palestine {
            get {
                return ResourceManager.GetString("Palestine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA.
        /// </summary>
        internal static string Panama {
            get {
                return ResourceManager.GetString("Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PG.
        /// </summary>
        internal static string Papua_New_Guinea {
            get {
                return ResourceManager.GetString("Papua New Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PY.
        /// </summary>
        internal static string Paraguay {
            get {
                return ResourceManager.GetString("Paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE.
        /// </summary>
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        internal static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PN.
        /// </summary>
        internal static string Pitcairn {
            get {
                return ResourceManager.GetString("Pitcairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        internal static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        internal static string Puerto_Rico {
            get {
                return ResourceManager.GetString("Puerto Rico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        internal static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE.
        /// </summary>
        internal static string Réunion {
            get {
                return ResourceManager.GetString("Réunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO.
        /// </summary>
        internal static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RU.
        /// </summary>
        internal static string Russian_Federation {
            get {
                return ResourceManager.GetString("Russian Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RW.
        /// </summary>
        internal static string Rwanda {
            get {
                return ResourceManager.GetString("Rwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL.
        /// </summary>
        internal static string Saint_Barthélemy {
            get {
                return ResourceManager.GetString("Saint Barthélemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH.
        /// </summary>
        internal static string Saint_Helena {
            get {
                return ResourceManager.GetString("Saint Helena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KN.
        /// </summary>
        internal static string Saint_Kitts_and_Nevis {
            get {
                return ResourceManager.GetString("Saint Kitts and Nevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        internal static string Saint_Lucia {
            get {
                return ResourceManager.GetString("Saint Lucia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF.
        /// </summary>
        internal static string Saint_Martin {
            get {
                return ResourceManager.GetString("Saint Martin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        internal static string Saint_Pierre_and_Miquelon {
            get {
                return ResourceManager.GetString("Saint Pierre and Miquelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        internal static string Saint_Vincent_and_the_Grenadines {
            get {
                return ResourceManager.GetString("Saint Vincent and the Grenadines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        internal static string Samoa {
            get {
                return ResourceManager.GetString("Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SM.
        /// </summary>
        internal static string San_Marino {
            get {
                return ResourceManager.GetString("San Marino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        internal static string Sao_Tome_and_Principe {
            get {
                return ResourceManager.GetString("Sao Tome and Principe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        internal static string Saudi_Arabia {
            get {
                return ResourceManager.GetString("Saudi Arabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string Scotland {
            get {
                return ResourceManager.GetString("Scotland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        internal static string Senegal {
            get {
                return ResourceManager.GetString("Senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        internal static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.
        /// </summary>
        internal static string Seychelles {
            get {
                return ResourceManager.GetString("Seychelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        internal static string Sierra_Leone {
            get {
                return ResourceManager.GetString("Sierra Leone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG.
        /// </summary>
        internal static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SX.
        /// </summary>
        internal static string Sint_Maarten {
            get {
                return ResourceManager.GetString("Sint Maarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK.
        /// </summary>
        internal static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        internal static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        internal static string Solomon_Islands {
            get {
                return ResourceManager.GetString("Solomon Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO.
        /// </summary>
        internal static string Somalia {
            get {
                return ResourceManager.GetString("Somalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZA.
        /// </summary>
        internal static string South_Africa {
            get {
                return ResourceManager.GetString("South Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS.
        /// </summary>
        internal static string South_Georgia_and_the_South_Sandwich_Islands {
            get {
                return ResourceManager.GetString("South Georgia and the South Sandwich Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        internal static string South_Sudan {
            get {
                return ResourceManager.GetString("South Sudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LK.
        /// </summary>
        internal static string Sri_Lanka {
            get {
                return ResourceManager.GetString("Sri Lanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        internal static string Sudan {
            get {
                return ResourceManager.GetString("Sudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        internal static string Suriname {
            get {
                return ResourceManager.GetString("Suriname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJ.
        /// </summary>
        internal static string Svalbard_and_Jan_Mayen {
            get {
                return ResourceManager.GetString("Svalbard and Jan Mayen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH.
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SY.
        /// </summary>
        internal static string Syria {
            get {
                return ResourceManager.GetString("Syria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TW.
        /// </summary>
        internal static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TJ.
        /// </summary>
        internal static string Tajikistan {
            get {
                return ResourceManager.GetString("Tajikistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TZ.
        /// </summary>
        internal static string Tanzania {
            get {
                return ResourceManager.GetString("Tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH.
        /// </summary>
        internal static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL.
        /// </summary>
        internal static string Timor_Leste {
            get {
                return ResourceManager.GetString("Timor-Leste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TG.
        /// </summary>
        internal static string Togo {
            get {
                return ResourceManager.GetString("Togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TK.
        /// </summary>
        internal static string Tokelau {
            get {
                return ResourceManager.GetString("Tokelau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        internal static string Tonga {
            get {
                return ResourceManager.GetString("Tonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT.
        /// </summary>
        internal static string Trinidad_and_Tobago {
            get {
                return ResourceManager.GetString("Trinidad and Tobago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TN.
        /// </summary>
        internal static string Tunisia {
            get {
                return ResourceManager.GetString("Tunisia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM.
        /// </summary>
        internal static string Turkmenistan {
            get {
                return ResourceManager.GetString("Turkmenistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        internal static string Turks_and_Caicos_Islands {
            get {
                return ResourceManager.GetString("Turks and Caicos Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string Tuvalu {
            get {
                return ResourceManager.GetString("Tuvalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UG.
        /// </summary>
        internal static string Uganda {
            get {
                return ResourceManager.GetString("Uganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA.
        /// </summary>
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE.
        /// </summary>
        internal static string United_Arab_Emirates {
            get {
                return ResourceManager.GetString("United Arab Emirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string United_Kingdom {
            get {
                return ResourceManager.GetString("United Kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        internal static string United_States {
            get {
                return ResourceManager.GetString("United States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UM.
        /// </summary>
        internal static string United_States_Minor_Outlying_Islands {
            get {
                return ResourceManager.GetString("United States Minor Outlying Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        internal static string United_States_of_America {
            get {
                return ResourceManager.GetString("United States of America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UY.
        /// </summary>
        internal static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZ.
        /// </summary>
        internal static string Uzbekistan {
            get {
                return ResourceManager.GetString("Uzbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VU.
        /// </summary>
        internal static string Vanuatu {
            get {
                return ResourceManager.GetString("Vanuatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VE.
        /// </summary>
        internal static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VN.
        /// </summary>
        internal static string Viet_Nam {
            get {
                return ResourceManager.GetString("Viet Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VI.
        /// </summary>
        internal static string Virgin_Islands {
            get {
                return ResourceManager.GetString("Virgin Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string Wales {
            get {
                return ResourceManager.GetString("Wales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WF.
        /// </summary>
        internal static string Wallis_and_Futuna {
            get {
                return ResourceManager.GetString("Wallis and Futuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EH.
        /// </summary>
        internal static string Western_Sahara {
            get {
                return ResourceManager.GetString("Western Sahara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YE.
        /// </summary>
        internal static string Yemen {
            get {
                return ResourceManager.GetString("Yemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZM.
        /// </summary>
        internal static string Zambia {
            get {
                return ResourceManager.GetString("Zambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZW.
        /// </summary>
        internal static string Zimbabwe {
            get {
                return ResourceManager.GetString("Zimbabwe", resourceCulture);
            }
        }
    }
}
